# Generated by Django 5.2.4 on 2025-08-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_projectpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedGroup',
            fields=[
                ('suggestedgroup_id', models.AutoField(primary_key=True, serialize=False)),
                ('strength', models.CharField(choices=[('strong', 'Strong Group'), ('medium', 'Medium Group'), ('weak', 'Weak Group')], max_length=6)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
