# Generated by Django 5.2.4 on 2025-08-03 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0003_suggestedgroup'),
        ('student_app', '0002_grouppreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalGroup',
            fields=[
                ('finalgroup_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_by_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_groups', to='project_app.project')),
            ],
        ),
        migrations.CreateModel(
            name='SuggestedGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_groups', to='student_app.student')),
                ('suggested_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='project_app.suggestedgroup')),
            ],
            options={
                'unique_together': {('suggested_group', 'student')},
            },
        ),
    ]
