# Generated by Django 5.2.4 on 2025-08-03 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0004_finalgroup_suggestedgroupmember'),
        ('student_app', '0002_grouppreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='project_app.finalgroup')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_groups', to='student_app.student')),
            ],
        ),
    ]
