# Generated by Django 5.2.4 on 2025-08-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0005_finalgroupmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='host_email',
            field=models.EmailField(default='unknown@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='host_name',
            field=models.CharField(default='Unknown Host', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='host_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
