# Generated by Django 5.2.4 on 2025-08-03 09:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0006_project_host_email_project_host_name_and_more'),
        ('student_app', '0003_grouppreference_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finalgroupmember',
            options={'ordering': ['student_id']},
        ),
        migrations.AlterModelOptions(
            name='suggestedgroupmember',
            options={'ordering': ['student_id']},
        ),
        migrations.AlterUniqueTogether(
            name='projectpreference',
            unique_together={('student', 'project'), ('student', 'rank')},
        ),
        migrations.AddField(
            model_name='projectpreference',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suggestedgroupmember',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='finalgroupmember',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_group_memberships', to='student_app.student'),
        ),
    ]
