# Generated by Django 5.2.4 on 2025-08-03 10:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0007_alter_finalgroupmember_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpreference',
            name='rank',
            field=models.PositiveBigIntegerField(verbose_name=django.core.validators.MinValueValidator(1)),
        ),
    ]
