# Generated by Django 5.2.4 on 2025-08-03 10:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0008_alter_projectpreference_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpreference',
            name='rank',
            field=models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
