# Generated by Django 5.2.4 on 2025-08-04 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0009_alter_projectpreference_rank'),
        ('student_app', '0003_grouppreference_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalgroupmember',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_group_member', to='student_app.student'),
        ),
    ]
