# Use an official Python runtime as a parent image
FROM python:3.10-slim-buster

# Set the working directory in the container
WORKDIR /app

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Install system dependencies
RUN apt-get update && apt-get install -y \
    postgresql-client \
    build-essential \
    libpq-dev \
    gcc \
    # Clean up APT when done to reduce image size
    && rm -rf /var/lib/apt/lists/*

# Copy the requirements file into the working directory
COPY requirements.txt .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of your Django project into the working directory
COPY . .

# Expose the port Django runs on (e.g., 8000)
EXPOSE 8000

# Command to run your Django development server
# You'll typically run migrations and then the server.
# This CMD can be overridden by docker-compose, which is typical for development.
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]