# Generated by Django 5.2.5 on 2025-08-17 18:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(db_index=True, max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('cwa', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('application_submitted', models.BooleanField(default=False)),
                ('allocated_group', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('major', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='admin_app.major')),
            ],
        ),
        migrations.CreateModel(
            name='GroupPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_type', models.CharField(choices=[('like', 'Would Like to Work With'), ('avoid', 'Would Prefer to Avoid')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_preferences', to='student_app.student')),
                ('target_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_preferences', to='student_app.student')),
            ],
            options={
                'unique_together': {('student', 'target_student')},
            },
        ),
    ]
