# Generated by Django 5.2.4 on 2025-08-03 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_type', models.CharField(choices=[('like', 'Would Like to Work With'), ('avoid', 'Would Prefer to Avoid')], max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_preferences', to='student_app.student')),
                ('target_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recieved_preferences', to='student_app.student')),
            ],
            options={
                'unique_together': {('student', 'target_student')},
            },
        ),
    ]
