# Generated by Django 5.2.4 on 2025-08-03 09:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0002_grouppreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppreference',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grouppreference',
            name='target_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_preferences', to='student_app.student'),
        ),
    ]
