# Generated by Django 5.2.5 on 2025-08-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0002_alter_student_cwa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(db_index=True, max_length=8, primary_key=True, serialize=False),
        ),
    ]
