# Generated by Django 5.2.6 on 2025-09-26 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0002_alter_student_email'),
        ('student_app', '0002_student_cv'),
    ]

    operations = [
    ]
