# Generated by Django 5.2.6 on 2025-09-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0003_merge_0002_alter_student_email_0002_student_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='split_group',
            field=models.BooleanField(default=False),
        ),
    ]
