# Generated by Django 5.2.5 on 2025-08-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0003_grouppreference_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='degree',
            field=models.CharField(default='Computing', max_length=100),
            preserve_default=False,
        ),
    ]
