# Generated by Django 5.2.6 on 2025-09-26 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0004_student_split_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='split_group',
            new_name='split_project',
        ),
    ]
