# Generated by Django 5.2.5 on 2025-08-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0004_student_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='group_allocated',
            field=models.BooleanField(default=False),
        ),
    ]
