# Generated by Django 5.2.5 on 2025-08-25 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_app', '0001_initial'),
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalgroupmember',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_group_member', to='student_app.student'),
        ),
        migrations.AddField(
            model_name='major',
            name='degree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='majors', to='admin_app.degree'),
        ),
        migrations.AddField(
            model_name='finalgroup',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_groups', to='admin_app.project'),
        ),
        migrations.AddField(
            model_name='projectpreference',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.project'),
        ),
        migrations.AddField(
            model_name='projectpreference',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.student'),
        ),
        migrations.AddField(
            model_name='round',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='rounds', to='admin_app.project'),
        ),
        migrations.AddField(
            model_name='suggestedgroupmember',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_groups', to='student_app.student'),
        ),
        migrations.AddField(
            model_name='suggestedgroupmember',
            name='suggested_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='admin_app.suggestedgroup'),
        ),
        migrations.AlterUniqueTogether(
            name='major',
            unique_together={('degree', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='projectpreference',
            unique_together={('student', 'project'), ('student', 'rank')},
        ),
        migrations.AlterUniqueTogether(
            name='suggestedgroupmember',
            unique_together={('suggested_group', 'student')},
        ),
    ]
