# Generated by Django 5.2.4 on 2025-08-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminlog',
            name='target_object_id',
        ),
        migrations.AddField(
            model_name='adminlog',
            name='target_id',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
