# Generated by Django 5.2.5 on 2025-09-18 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='is_internal',
            field=models.BooleanField(default=False),
        ),
    ]
