# Generated by Django 5.2.5 on 2025-08-21 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('round_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('upcoming', 'Upcoming')], max_length=10)),
                ('open_date', models.DateTimeField()),
                ('close_date', models.DateTimeField()),
                ('projects', models.ManyToManyField(blank=True, related_name='rounds', to='admin_app.project')),
            ],
        ),
    ]
