# Generated by Django 5.2.5 on 2025-08-21 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('round_id', models.AutoField(primary_key=True, serialize=False)),
                ('round_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('upcoming', 'Upcoming')], max_length=10)),
                ('open_date', models.DateTimeField()),
                ('close_date', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='rounds',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='admin_app.round'),
        ),
    ]
