# Generated by Django 5.2.5 on 2025-08-21 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
