# Generated by Django 5.2.6 on 2025-09-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_finalgroup_name_suggestedgroup_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestedgroup',
            name='has_anti_preference',
            field=models.BooleanField(default=False),
        ),
    ]
