# Generated by Django 5.2.5 on 2025-08-25 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_round_project_rounds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='rounds',
        ),
        migrations.AddField(
            model_name='round',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='rounds', to='admin_app.project'),
        ),
    ]
