# Generated by Django 5.2.5 on 2025-08-27 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_unitcontacts_capstoneinformationsection_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capstoneinformationsection',
            options={'ordering': ['order', 'id']},
        ),
    ]
