# Generated by Django 5.2.6 on 2025-09-04 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_suggestedgroup_has_anti_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestedgroup',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='suggested_groups', to='admin_app.project'),
            preserve_default=False,
        ),
    ]
