# Generated by Django 5.2.5 on 2025-08-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_alter_capstoneinformationsection_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='capstoneinformationcontent',
            index=models.Index(fields=['section_id', '-pinned', 'priority', '-published_at'], name='admin_app_c_section_5e2edc_idx'),
        ),
        migrations.AddIndex(
            model_name='capstoneinformationcontent',
            index=models.Index(fields=['status', 'published_at', 'expires_at'], name='admin_app_c_status_520094_idx'),
        ),
    ]
