# Generated by Django 5.2.6 on 2025-09-04 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_suggestedgroup_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestedgroup',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggested_groups', to='admin_app.project'),
        ),
    ]
