# Generated by Django 5.2.6 on 2025-09-14 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_alter_suggestedgroup_project'),
        ('student_app', '0002_alter_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestedgroup',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='projectpreference',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='student_app.student'),
        ),
    ]
