# Generated by Django 5.2.6 on 2025-09-26 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_round_is_internal'),
        ('admin_app', '0007_suggestedgroup_is_manual_and_more'),
    ]

    operations = [
    ]
