# Generated by Django 5.2.6 on 2025-09-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0008_merge_20250926_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='is_internal',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='round',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('upcoming', 'Upcoming')], default='upcoming', max_length=10),
        ),
    ]
