# Generated by Django 5.2.7 on 2025-10-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0009_alter_round_is_internal_alter_round_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capstoneinformationcontent',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='capstoneinformationcontent',
            name='pinned',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='capstoneinformationcontent',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='capstoneinformationcontent',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='published', max_length=20),
        ),
    ]
