# Generated by Django 5.2.7 on 2025-10-16 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0010_alter_capstoneinformationcontent_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('EDIT', 'Edit'), ('DELETE', 'Delete'), ('ASSIGN', 'Assign Student'), ('USER_CREATED', 'User Created'), ('LOGIN', 'User Logged In'), ('LOGOUT', 'User Logged Out'), ('GROUP_CREATED', 'Group Created'), ('GROUP_UPDATED', 'Group Updated'), ('GROUP_DELETED', 'Group Deleted')], max_length=50),
        ),
        migrations.AlterField(
            model_name='suggestedgroup',
            name='strength',
            field=models.CharField(choices=[('strongest', 'Strongest Group'), ('strong', 'Strong Group'), ('medium', 'Medium Group'), ('weak', 'Weak Group')], max_length=9),
        ),
    ]
