# This file will define the URL endpoints for your API.
# DRF's routers can automatically generate a full set of
# URL patterns for a ViewSet, which simplifies things immensely.

from rest_framework.routers import DefaultRouter
from django.urls import path, include
from . import views
from admin_app.api.views import admin_views, round_views, project_views, group_views, degree_views

app_name = 'api_admin'

router = DefaultRouter()
#Admin_views ViewSet
router.register(r'admin-logs', admin_views.AdminLogViewSet, basename='admin_log')
#Round_views
router.register(r'rounds', round_views.RoundViewSet, basename='round')
#Project_views
router.register(r'projects', project_views.ProjectViewSet, basename='project')
router.register(r'project_preferences', project_views.ProjectPreferencesViewSet, basename='project_preference')
#Groups_views
router.register(r'suggested_groups', group_views.SuggestedGroupViewSet, basename='suggested_group')
router.register(r'suggested_group_members', group_views.SuggestedGroupMemberViewSet, basename='suggested_group_member')
router.register(r'final_groups', group_views.FinalGroupViewSet, basename='final_group')
router.register(r'final_group_members', group_views.FinalGroupMemberViewSet, basename='final_group_member')
#Degrees_views
router.register(r'degrees', degree_views.DegreeViewSet, basename='degree')
router.register(r'majors', degree_views.MajorViewSet, basename='major')

urlpatterns = [
    #Include all urls generated by router (View Sets)
    path('', include(router.urls)),

    #Custom API views for email notifications
    path("notify/round-start/<int:round_id>/", admin_views.SendRoundStartView.as_view(), name="notify_round_start"),
    path("notify/round-closed/<int:round_id>/", admin_views.SendRoundClosedView.as_view(), name="notify_round_closed"),
    path("notify/application-success/<str:student_id>/", admin_views.SendApplicationSuccessView.as_view(), name="notify_application_success"),
    path("notify/allocation-released/<int:final_group_id>/", admin_views.SendAllocationReleasedView.as_view(), name="notify_allocation_released"),
]

