# This file will define the URL endpoints for your API.
# DRF's routers can automatically generate a full set of
# URL patterns for a ViewSet, which simplifies things immensely.

from rest_framework.routers import DefaultRouter
from django.urls import path, include
from . import views
from admin_app.api.views import admin_views, round_views, project_views, group_views, degree_views, student_api_views, email_views

app_name = 'api_admin'

router = DefaultRouter()
#Admin_views ViewSet
router.register(r'admin-logs', admin_views.AdminLogViewSet, basename='admin_log')
#Round_views
router.register(r'rounds', round_views.RoundViewSet, basename='round')
#Project_views
router.register(r'projects', project_views.ProjectViewSet, basename='project')
router.register(r'project_preferences', project_views.ProjectPreferencesViewSet, basename='project_preference')
#Groups_views
router.register(r'suggested_groups', group_views.SuggestedGroupViewSet, basename='suggested_group')
router.register(r'suggested_group_members', group_views.SuggestedGroupMemberViewSet, basename='suggested_group_member')
router.register(r'final_groups', group_views.FinalGroupViewSet, basename='final_group')
router.register(r'final_group_members', group_views.FinalGroupMemberViewSet, basename='final_group_member')
#Degrees_views
router.register(r'degrees', degree_views.DegreeViewSet, basename='degree')
router.register(r'majors', degree_views.MajorViewSet, basename='major')

urlpatterns = [

    #Custom API views for email notifications
    path("notify/round-start/<int:round_id>/", admin_views.SendRoundStartView.as_view(), name="notify_round_start"),
    path("notify/round-closed/<int:round_id>/", admin_views.SendRoundClosedView.as_view(), name="notify_round_closed"),
    path("notify/application-success/<str:student_id>/", admin_views.SendApplicationSuccessView.as_view(), name="notify_application_success"),
    path("notify/allocation-released/<int:final_group_id>/", admin_views.SendAllocationReleasedView.as_view(), name="notify_allocation_released"),

    #Email custom views
    path("email/mailto/", email_views.MailtoLinkView.as_view(), name="mailto_link"),
    path("projects/<int:project_id>/resumes/", email_views.ProjectResumesView.as_view(), name="project_resumes"),
    path("projects/<int:project_id>/resumes/zip/", email_views.ProjectResumesZipView.as_view(), name="project_resumes_zip"),

    #Custom Group API views
    path("suggested_groups/", group_views.SuggestedGroupListCreateView.as_view(), name="suggested-group-list"),
    path("suggested_groups/<int:suggestedgroup_id>/", group_views.SuggestedGroupDetailView.as_view(), name="suggested-group-detail"),
    path("suggested_members/", group_views.SuggestedGroupMemberListCreateView.as_view(), name="suggested-group-member-list"),
    path("generate_suggestions/", group_views.GenerateSuggestionsView.as_view(), name="generate_suggestions"),
    path("suggested_groups/<int:suggestedgroup_id>/remove_student/", group_views.remove_student_from_group),
    path("suggested_groups/<int:suggestedgroup_id>/add_student/", group_views.add_student_to_group),
    path("suggested_groups/<int:suggestedgroup_id>/update/", group_views.SuggestedGroupUpdateView.as_view(), name="suggestedgroup-update"),
    path("suggested_groups/create_manual/", group_views.create_manual_group, name="create_manual_group"),
    path("suggested_groups/manual/", group_views.ManualGroupListView.as_view(), name="manual-groups"),
    path("suggested_groups/<int:suggestedgroup_id>/delete/", group_views.delete_manual_group, name="delete-manual-group"),
    path("suggested_groups/auto/", group_views.SuggestedGroupLiteListView.as_view(), name="suggested-groups-auto"),
    path("final_groups/", group_views.FinalGroupCreateView.as_view(), name="final-group-create"),
    path("final_groups/list/", group_views.FinalGroupListView.as_view(), name="final-group-list"),

    #Student custom API views
    path("students/", student_api_views.StudentListCreateAPIView.as_view(), name="student_list"),
    path("students/import/", student_api_views.StudentImportAPIView.as_view(), name="student_import"),
    path("students/<pk>/", student_api_views.StudentRetrieveUpdateDestroyAPIView.as_view(), name="student_detail"),
    path("students/<pk>/notes/", student_api_views.StudentNotesUpdateAPIView.as_view(), name="student_notes_update"),

    #Include all urls generated by router (View Sets)
    path('', include(router.urls)),
]

